/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_zhost_jni_HelloWorldJNI */

#ifndef _Included_top_zhost_jni_HelloWorldJNI
#define _Included_top_zhost_jni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_zhost_jni_HelloWorldJNI
 * Method:    helloJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_top_zhost_jni_HelloWorldJNI_helloJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
